#!/bin/bash

## trap "pkill -P $$" SIGINT
## trap "pkill -P $$" EXIT
  
# while true ; do
#     temp3=`sensors | grep 'temp3' | awk '{print $2}'`
#     core0=`sensors | grep 'Core 0' | awk '{print $3}'`
#     echo -n "Core 0: " $core0 " | temp3 :" $temp3
#     sleep 60
# done

while true ; do
    echo -n "temp3: "
    sensors | grep 'temp3' | awk '{print $2}'
    sleep 60
done
